### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'output_cmscan.txt'

### ISSUE THREAD

**Issue by kangkang042** [BackofenLab/CRISPRtracrRNA#3]
Hi, I got an error: "FileNotFoundError: [Errno 2] No such file or directory: 'output_cmscan.txt'".
How can I get this problem solved ?

**Comment by sbenler** [comment]
I ran into the same issue. For me, it was caused by two problems: 1) a permissions issue with the fasta36 tool. I updated the permissions  with `chmod` and the tool ran the test successfully. 2) a non-fasta file in the `--input` folder directory. The tool ran successfully after removing that file

**Comment by kangkang042** [comment]
I used `chmod `to change the permission status of fasta36. But that error goes on,  "FileNotFoundError: [Errno 2] No such file or directory: 'output_cmscan.txt'"

```
Creating` folders if necessary...
Running CRISPR array search, it may take a while...
Running CRISPR cas search, it may take a while...
                Working with 1 files


                Working with file 1 - AAAIBU010000002.fasta
1. Searching for anti repeats
2. Filtering Anti-repeats
3. Forming initial TracrRNA candidates
4. Improving the results using CRISPRRNA-TracrRNA interaction prediction
5. Searching for the terminator sequences
6. Searching the hits with the provided tail model
Traceback (most recent call last):
  File "CRISPRtracrRNA.py", line 46, in <module>
    main()
  File "CRISPRtracrRNA.py", line 36, in main
    dict_weights=dict_weights)
  File "/home/kk/CRISPRtracrRNA/modules/pipelines.py", line 35, in __init__
    self._pipeline_run()
  File "/home/kk/CRISPRtracrRNA/modules/pipelines.py", line 142, in _pipeline_run
    cm_scan_on_candidates = CMScanOnCandidates(all_tracr_sequences_global_window, self.hmm_model)
  File "/home/kk/CRISPRtracrRNA/modules/hmm_model_run.py", line 18, in __init__
    self._parse_result_file()
  File "/home/kk/CRISPRtracrRNA/modules/hmm_model_run.py", line 65, in _parse_result_file
    with open("output_cmscan.txt") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'output_cmscan.txt'
```

**Comment by lawrence-ip** [comment]
I had the same issue, this can be resolved by using `chmod` on all of their binaries and executables.

**Comment by kangkang042** [comment]
Thanks very much! It really worked!i😁

**Comment by Golden-proteogenomics** [comment]
Could you tell me detail about · using chmod on all of their binaries and executables.·? because I use ·chmod a+x  ./tools·, there are still errors like above.

**Comment by kangkang042** [comment]
You can try "chmod 777" with all the files in ./CRISPRtracrRNA

**Comment by zhp2333** [comment]
hi @allenk42 
I have encountered the same problem as you, I used your method, use `chmod -R 777 * ` or `chmod -R 777 ./CRISPRtracrRNA`
All my files in this folder are `-rwxrwxrwx` . But unable to solve my problem. Here is my usage code and error report.

```
python CRISPRtracrRNA.py   --input_folder cas14input/ --output_folder cas14output/ --output_summary_file cas14_result.csv --model_type V --perform_type_v_anti_repeat_analysis ture

Running CRISPR array search, it may take a while...
Running CRISPR cas search, it may take a while...
                Working with 3 files


                Working with file 1 - cas14a1.fasta
1. Searching for anti repeats
2. Filtering Anti-repeats
3. Forming initial TracrRNA candidates
4. Improving the results using CRISPRRNA-TracrRNA interaction prediction
5. Searching for the terminator sequences
6. Searching the hits with the provided tail model
Traceback (most recent call last):
  File "CRISPRtracrRNA.py", line 46, in <module>
    main()
  File "CRISPRtracrRNA.py", line 36, in main
    dict_weights=dict_weights)
  File "/mnt/f/生信数据/CRISPRtracrRNA/modules/pipelines.py", line 35, in __init__
    self._pipeline_run()
  File "/mnt/f/生信数据/CRISPRtracrRNA/modules/pipelines.py", line 142, in _pipeline_run
    cm_scan_on_candidates = CMScanOnCandidates(all_tracr_sequences_global_window, self.hmm_model)
  File "/mnt/f/生信数据/CRISPRtracrRNA/modules/hmm_model_run.py", line 18, in __init__
    self._parse_result_file()
  File "/mnt/f/生信数据/CRISPRtracrRNA/modules/hmm_model_run.py", line 65, in _parse_result_file
    with open("output_cmscan.txt") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'output_cmscan.txt'
```
Anyway, thank you for your help!

**Comment by kangkang042** [comment]
首先试试把文件夹上的中文都改成英文吧😂

**Comment by zhp2333** [comment]
大佬，改了还是没用。头疼了😭
```
Creating folders if necessary...
Running CRISPR array search, it may take a while...
Running CRISPR cas search, it may take a while...
                Working with 3 files


                Working with file 1 - cas14a1.fasta
1. Searching for anti repeats
2. Filtering Anti-repeats
3. Forming initial TracrRNA candidates
4. Improving the results using CRISPRRNA-TracrRNA interaction prediction
5. Searching for the terminator sequences
6. Searching the hits with the provided tail model
Traceback (most recent call last):
  File "CRISPRtracrRNA.py", line 46, in <module>
    main()
  File "CRISPRtracrRNA.py", line 36, in main
    dict_weights=dict_weights)
  File "/mnt/f/Bioinformatics_data/CRISPRtracrRNA/modules/pipelines.py", line 35, in __init__
    self._pipeline_run()
  File "/mnt/f/Bioinformatics_data/CRISPRtracrRNA/modules/pipelines.py", line 142, in _pipeline_run
    cm_scan_on_candidates = CMScanOnCandidates(all_tracr_sequences_global_window, self.hmm_model)
  File "/mnt/f/Bioinformatics_data/CRISPRtracrRNA/modules/hmm_model_run.py", line 18, in __init__
    self._parse_result_file()
  File "/mnt/f/Bioinformatics_data/CRISPRtracrRNA/modules/hmm_model_run.py", line 65, in _parse_result_file
    with open("output_cmscan.txt") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'output_cmscan.txt'
```

**Comment by Golden-proteogenomics** [comment]
Please allow me to respond in Chinese.
根据我的使用经验来看，这个报错是不影响最终结果的。这个结果报错，更多的是在你的序列中没有找到适合条件的arry信息。

**Comment by zhp2333** [comment]
@Golden-proteogenomics 

Thanks for your help, I will test with more sequences of cas12 system next.
谢谢大佬，我再用别的cas12序列试试。

**Comment by N-yating** [comment]
the same problem happens to me, so could you help me !!!!
