### ISSUE TITLE
Got error "IndexError: list index out of range", line 10 in consistency_score_maker.py

### ISSUE THREAD

**Issue by wuke030** [BackofenLab/CRISPRtracrRNA#4]
Hi, 
I got an error "IndexError: list index out of range".
`Traceback (most recent call last):
File "/CRISPRtracrRNA-main/CRISPRtracrRNA.py", line 46, in <module>
    main()
  File "/CRISPRtracrRNA-main/CRISPRtracrRNA.py", line 36, in main
    dict_weights=dict_weights)
  File "/CRISPRtracrRNA-main/modules/pipelines.py", line 35, in __init__
    self._pipeline_run()
  File "/CRISPRtracrRNA-main/modules/pipelines.py", line 316, in _pipeline_run
    consistency_score_maker(self.output_file_name, ",", self.output_file_name)
  File "/CRISPRtracrRNA-main/modules/consistency_score_maker.py", line 10, in consistency_sc>
    header, info_lines = lines[0], lines[1:]
IndexError: list index out of range
`

My input folder contains 7 fasta files and use command:
`python /CRISPRtracrRNA-main/CRISPRtracrRNA.py --input_folder /data/tracrRNA_predict/ga/fasta`

Could you please help solve this problem, thanks a lot.

**Comment by mhyleung** [comment]
Dear all

I am getting this exact same error code but I can't seem to figure out what the reason is. Seems like it's a closed issue so there was a solution? Thanks

Marc
