### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'ResultsIdentify/Complete_summary.csv'

### ISSUE THREAD

**Issue by lnguyen1991** [BackofenLab/CRISPRtracrRNA#7]
I get the following errors:
Creating folders if necessary...
Running CRISPR array search, it may take a while...
Traceback (most recent call last):
  File "CRISPRtracrRNA.py", line 46, in <module>
    main()
  File "CRISPRtracrRNA.py", line 29, in main
    complete_tracr_search = CompleteTracrSearchWithModel(folder_output=folder_output,
  File "/Users/longnguyen/CRISPRtracrRNA/modules/pipelines.py", line 35, in __init__
    self._pipeline_run()
  File "/Users/longnguyen/CRISPRtracrRNA/modules/pipelines.py", line 44, in _pipeline_run
    dict_arrays = CRISPRIdentifySummaryParser(crispr_identify_summary_file).output()
  File "/Users/longnguyen/CRISPRtracrRNA/modules/crispr_identify_summary_parser.py", line 18, in __init__
    self._parse_file()
  File "/Users/longnguyen/CRISPRtracrRNA/modules/crispr_identify_summary_parser.py", line 21, in _parse_file
    with open(self.summary_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'ResultsIdentify/Complete_summary.csv'

**Comment by Huanle** [comment]
Hi @lnguyen1991 ,

Have you solved the issue.
I ran into the same. It would greatly help me if you have a solution.

Cheers - Huanle

**Comment by Huanle** [comment]
Ok. I found the solution:
- link downloaded repositories for CRISPRidentify and CRISPRcasIdentifier inside the **tools** folder. Linking only *py scripts is not enough.
- make software under **tools/infernal/binaries/** executable.

**Comment by lnguyen1991** [comment]
I have not been able to fix it. Can you elaborate on how you fixed it?

**Comment by Alexander-Mitrofanov** [comment]
Thank you for expressing interest in our tool. We aim to implement the necessary fixes within the next two weeks.

**Comment by Huanle** [comment]
> I have not been able to fix it. Can you elaborate on how you fixed it?

lnside *tools/CRISPRidentify/*, i have:
CRISPRidentify -> ../../../CRISPRidentify/

Inside *tools/CRISPRcasIdentifier*, i have:
CRISPRcasIdentifier -> ../../../CRISPRcasIdentifier-1.1.0/

CRISPRidentify and CRISPRcasIdentifier-1.1.0 were installed somewhere else.

I made programs in *tools/infernal/binaries/* executable.
