### ISSUE TITLE
How to deal with "list index out of range"

### ISSUE THREAD

**Issue by N-yating** [BackofenLab/CRISPRtracrRNA#9]
Creating folders if necessary...
Running CRISPR array search, it may take a while...
Running CRISPR cas search, it may take a while...
		Working with 5 files 

		Working with file 1 - TARA_Cas9_22.fa
		Working with file 2 - TARA_Cas9_12.fa
		Working with file 3 - TARA_Cas9_13.fa
		Working with file 4 - TARA_Cas9_15.fa
		Working with file 5 - TARA_Cas9_20.fa

		Creating the final_summary

		Adding consistency scores to the final summary file
Traceback (most recent call last):
  File "CRISPRtracrRNA.py", line 47, in <module>
    main()
  File "CRISPRtracrRNA.py", line 37, in main
    dict_weights=dict_weights)
  File "/share/home/bgi_liusifan/CRISPRtracrRNA-main/modules/pipelines.py", line 35, in __init__
    self._pipeline_run()
  File "/share/home/bgi_liusifan/CRISPRtracrRNA-main/modules/pipelines.py", line 316, in _pipeline_run
    consistency_score_maker(self.output_file_name, ",", self.output_file_name)
  File "/share/home/bgi_liusifan/CRISPRtracrRNA-main/modules/consistency_score_maker.py", line 10, in consistency_score_maker
    header, info_lines = lines[0], lines[1:]
IndexError: list index out of range

**Comment by N-yating** [comment]
it seems like olny the examples can run, how can I solve this problem?

**Comment by richardstoeckl** [comment]
`CRISPRtracrRNA` is currently not set-up to deal with input fasta files that contain multiple sequences (e.g. contigs) in one file.

As a workaround, you can treat your individual contigs as different genomes and provide them in seperate files within the input folder.
To split your fasta file by sequence header, you could use something like `seqkit`like this:

```bash
seqkit replace -p "\s.+" fasta_with_multiple_contigs.fna | seqkit split --by-id --two-pass --out-dir split_dir/
```

Note: You should also rename the resulting split fasta files to something short like "contig1.fasta" etc., to avoid other problems :)
